require('reflect-metadata');
const {test}=require('node:test');const assert=require('node:assert/strict');
const {createConnection}=require('mongoose');const {generateKeyPairSync,createPublicKey,randomUUID}=require('node:crypto');const {mkdtempSync}=require('node:fs');const {tmpdir}=require('node:os');
const {SignJWT,EncryptJWT,jwtVerify,jwtDecrypt,createLocalJWKSet}=require('jose');
const {GoogleMailerBroker,GmailOAuthStateSchema}=require('/app/dist/google-mailer.js');const {SigningService}=require('/app/dist/security.js');const security=require('/app/dist/security.js');const {SchoolSchema,ReplaySchema}=require('/app/dist/models.js');const {setDataDir}=require('/app/dist/config.js');
process.env.GOOGLE_OAUTH_CLIENT_ID='unit-client';process.env.GOOGLE_OAUTH_CLIENT_SECRET='unit-secret';setDataDir(mkdtempSync(tmpdir()+'/cs-broker-test-'));
test('broker real Mongo school signatures, persistent replay, PKCE state/browser binding, callback and encrypted refresh',async t=>{
 const db=await createConnection(process.env.MONGO_URI).asPromise(),schools=db.model('School',SchoolSchema),replays=db.model('Replay',ReplaySchema),states=db.model('GmailOAuthState',GmailOAuthStateSchema);await Promise.all([schools.init(),replays.init(),states.init()]);
 const settings={issuer:async()=> 'https://central.test',get:async()=>({corsOrigins:['https://web.test']})},signing=new SigningService(settings);await signing.onModuleInit();const keys=generateKeyPairSync('ed25519'),rsa=generateKeyPairSync('rsa',{modulusLength:2048}),schoolPublicKey=keys.publicKey.export({type:'spki',format:'pem'}),encryptionPublicKey=rsa.publicKey.export({type:'spki',format:'pem'}),broker=new GoogleMailerBroker(schools,replays,states,settings,signing);
 const signed=async(action,claims,jti=randomUUID())=>({assertion:await new SignJWT({action,...claims}).setProtectedHeader({alg:'EdDSA'}).setIssuer('sss').setAudience('https://central.test').setIssuedAt().setExpirationTime('5m').setJti(jti).sign(keys.privateKey)});
 const decode=async b=>{const p=(await jwtVerify(b.assertion,createLocalJWKSet(signing.jwks()),{issuer:'https://central.test',audience:'sss',algorithms:['EdDSA']})).payload;assert(!b.assertion.includes('fake_refresh_token'));return (await jwtDecrypt(p.encrypted,rsa.privateKey,{issuer:'https://central.test',audience:'sss',keyManagementAlgorithms:['RSA-OAEP-256'],contentEncryptionAlgorithms:['A256GCM']})).payload;};
 try{
 await schools.create({schoolCode:'sss',name:'Test',baseUrl:'https://school.test',publicKey:schoolPublicKey,trusted:true});
 const connectClaims={connectId:'a'.repeat(64),encryptionPublicKey,returnOrigin:'https://web.test'},req=await signed('connect',connectClaims),created=await broker.connect(req);assert.equal(new URL(created.url).origin,'https://central.test');await assert.rejects(broker.connect(req));await assert.rejects(new GoogleMailerBroker(schools,replays,states,settings,signing).connect(req));
 await assert.rejects(broker.connect(await signed('connect',{...connectClaims,returnOrigin:'https://attacker.test'})));await assert.rejects(broker.connect({assertion:req.assertion.slice(0,-10)+'A'.repeat(10)}));
 const ticket=new URL(created.url).searchParams.get('ticket'),started=await broker.start(ticket),authUrl=new URL(started.url),state=authUrl.searchParams.get('state');assert.equal(authUrl.searchParams.get('access_type'),'offline');assert.equal(authUrl.searchParams.get('prompt'),'consent');assert.equal(authUrl.searchParams.get('code_challenge_method'),'S256');assert(authUrl.searchParams.get('scope').includes('gmail.send'));await assert.rejects(broker.start(ticket));
 await assert.rejects(broker.callback({state,code:'fake_code'},started.cookieName+'=wrong'));assert.equal((await states.findOne({id:ticket}).lean()).consumed,false);
 const pending=await states.findOne({id:ticket}).lean();t.mock.method(broker,'identity',async()=>({nonce:pending.nonce,email_verified:true,email:'sender@test.edu'}));let delivered=0,refreshCalls=0;
 t.mock.method(globalThis,'fetch',async(url,init)=>{assert.equal(url,'https://oauth2.googleapis.com/token');assert.equal(init.redirect,'error');const fields=new URLSearchParams(init.body);assert.equal(fields.get('client_id'),'unit-client');if(fields.get('grant_type')==='authorization_code'){assert.equal(fields.get('code_verifier'),pending.verifier);return Response.json({access_token:'fake_access_token',refresh_token:'fake_refresh_token',id_token:'fake_id_token',scope:'https://www.googleapis.com/auth/gmail.send openid email',token_type:'Bearer',expires_in:3600});}refreshCalls++;assert.equal(fields.get('refresh_token'),'fake_refresh_token');return Response.json({access_token:'fake_refreshed_access',scope:'https://www.googleapis.com/auth/gmail.send',token_type:'Bearer',expires_in:3600});});
 t.mock.method(security,'publicJson',async(url,body)=>{delivered++;assert.equal(url.href,'https://school.test/mailer/google/callback');const p=await decode(body);assert.equal(p.refreshToken,'fake_refresh_token');assert.equal(p.email,'sender@test.edu');assert.equal(p.connectId,connectClaims.connectId);return {ok:true};});
 const callback=await broker.callback({state,code:'fake_code'},started.cookieName+'='+started.browser);assert.equal(new URL(callback.url).searchParams.get('mailer'),'connected');assert.equal(delivered,1);await assert.rejects(broker.callback({state,code:'fake_code'},started.cookieName+'='+started.browser));
 const keyAssertion=(await jwtVerify((await broker.key()).assertion,createLocalJWKSet(signing.jwks()),{issuer:'https://central.test',audience:'carpschool-gmail-broker'})).payload,requestId=randomUUID(),encrypted=await new EncryptJWT({requestId,refreshToken:'fake_refresh_token'}).setProtectedHeader({alg:'RSA-OAEP-256',enc:'A256GCM'}).setIssuer('sss').setAudience('https://central.test').setIssuedAt().setExpirationTime('5m').setJti(requestId).encrypt(createPublicKey(keyAssertion.publicKey));
 const refreshRequest=await signed('refresh',{encrypted,encryptionPublicKey},requestId),refreshed=await decode(await broker.refresh(refreshRequest));assert.equal(refreshed.requestId,requestId);assert.equal(refreshed.accessToken,'fake_refreshed_access');assert.equal(refreshCalls,1);await assert.rejects(broker.refresh(refreshRequest));
 await schools.updateOne({schoolCode:'sss'},{$set:{enabled:false}});await assert.rejects(broker.connect(await signed('connect',connectClaims)));assert.equal(delivered,1);
 }finally{await db.dropDatabase();await db.close();}
});
